version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
 
- package-ecosystem: nuget
  directory: "/WorkerService1"
  schedule:
    interval: weekly
  commit-message:
    prefix: chore