name: Release on push on main branch
 
on:
  push:
    branches:
      - main
 
jobs:
  release-on-push-on-main-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
 
      - name: Install Node dependencies
        run: npm install
 
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
 
      - name: Install .Net dependencies
        run: dotnet restore ./WorkerService1
 
      - name: Run build
        run: dotnet build ./WorkerService1
 
      - name: Fetch release version
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main --dry-run
 
      - name: Publish WorkerService1
        run: dotnet publish ./WorkerService1/WorkerService1 -p:Version=${{ env.RELEASE_VERSION }} -o Project
 
      - name: ZIP Project directory
        run: zip -r Project.zip Project
 
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main