name: Run lint on pull request
 
on: pull_request
 
jobs:
  run-lint-on-pull-request:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
 
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format
 
      - name: Run lint
        run: dotnet format ./SolutionDir --verify-no-changes --verbosity diagnostic